services:
  grafana:
    image: grafana/grafana-enterprise:latest
    container_name: grafana
    restart: always
    user: root
    volumes:
      - ./grafana/data:/var/lib/grafana
    ports:
      - 3000:3000
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    user: root
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./prometheus/data:/prometheus
  clash-exporter:
    image: zzde/clash-exporter:latest
    container_name: clash-exporter
    entrypoint:
      ["/app/clash-exporter", "-collectTracing=true", "-collectDest=true"]
    environment:
      - CLASH_HOST=12.0.0.1:9090
      - CLASH_TOKEN=
    restart: always
    ports:
      - 2112:2112
