name: Publish to ghcr

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:

jobs:
  plan:
    name: Plan 
    runs-on: ubuntu-latest
    steps:
      - name: Application Options
        id: options
        shell: bash
        working-directory: .
        run: |
          PLATFORMS=$(\
              docker buildx bake image-all --print --progress=quiet \
                  | jq --raw-output --compact-output '.target."image-all".platforms' \
          )
          SOURCE=$(\
              docker buildx bake --list type=variables,format=json --progress=quiet \
                  | jq --raw-output '.[] | select(.name == "SOURCE") | .value' \
          )
          VERSION=$(\
              docker buildx bake --list type=variables,format=json --progress=quiet \
                  | jq --raw-output '.[] | select(.name == "VERSION") | .value' \
          )

          echo "platforms=${PLATFORMS}" >> $GITHUB_OUTPUT
          echo "source=${SOURCE}" >> $GITHUB_OUTPUT
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

  build:
    needs: plan
    name: Build (${{ matrix.platform }})
    runs-on: ubuntu-latest
    strategy: 
      fail-fast: false
      matrix: 
        platform: ["linux/amd64", "linux/arm64"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # v3.0.0

      - name: Build Application Metadata
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
        id: meta
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index
        with:
          flavor: latest=false
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ inputs.app }}
          tags: |
            type=semver,pattern={{version}},value=${{ steps.app-versions.outputs.semantic }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.app-versions.outputs.semantic }},enable=${{ steps.app-versions.outputs.is-valid-semver }}
            type=semver,pattern={{major}},value=${{ steps.app-versions.outputs.semantic }},enable=${{ steps.app-versions.outputs.is-valid-semver }}
            type=raw,value=${{ steps.app-versions.outputs.raw }},enable=${{ steps.app-versions.outputs.is-valid-semver }}
            type=raw,value=rolling

            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,event=branch,enable={{is_default_branch}}
          flavor: |
            latest=auto

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5 # v5.0.0
        with:
          provenance: false
          context: ./config_v5
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache,mode=max

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.IMAGE_NAME }}
