name: Publish to ghcr

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:
    inputs:
      version: 
        type: string
        description: "指定版本"
        required: false
      release: 
        type: boolean
        description: "推送"
        required: false
        default: false

env:
  APP: clash-exporter

jobs:
  plan:
    name: Plan
    outputs:
      app: ${{ steps.options.outputs.app }}
      version: ${{ steps.options.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Application Options
        id: options
        shell: bash
        working-directory: .
        run: |
          PLATFORMS=$(\
              docker buildx bake image-all --print --progress=quiet -f docker-bake.hcl \
                  | jq --raw-output --compact-output '.target."image-all".platforms' \
          )
          SOURCE=$(\
              docker buildx bake --list type=variables,format=json --progress=quiet -f docker-bake.hcl \
                  | jq --raw-output '.[] | select(.name == "SOURCE") | .value' \
          )
          APP=$(\
              docker buildx bake --list type=variables,format=json --progress=quiet -f docker-bake.hcl \
                  | jq --raw-output '.[] | select(.name == "APP") | .value' \
          )
          if [ -n "${{ inputs.version }}" ]; then
            VERSION="${{ inputs.version }}"
          else
            VERSION="${{ github.ref_name }}"
          fi
          if [ -z "$VERSION"  ]; then
            echo "version is missing, exiting..."
            exit 1
          fi
          VERSION="${VERSION#v}"

          echo "platforms=${PLATFORMS}" >> $GITHUB_OUTPUT
          echo "source=${SOURCE}" >> $GITHUB_OUTPUT
          echo "app=${APP}" >> $GITHUB_OUTPUT
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
  build:
    needs: plan
    name: Build (${{ matrix.platform }})
    runs-on: ${{ startsWith(matrix.platform, 'linux/arm') && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    permissions:
      packages: write
    strategy: 
      fail-fast: false
      matrix: 
        platform: ["linux/amd64", "linux/arm64"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Target Architecture
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        id: target
        with:
          script: |
            core.setOutput('arch', '${{ matrix.platform }}'.split('/').pop());
    
      - name: Login to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # v3.0.0

      - name: Build Application Metadata
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
        id: meta
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index
        with:
          flavor: latest=false
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ needs.plan.outputs.app }}
          tags: |
            type=semver,pattern={{version}},value=${{ needs.plan.outputs.version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ needs.plan.outputs.version }}
            type=semver,pattern={{major}},value=${{ needs.plan.outputs.version }}
            type=raw,value=rolling

      - name: Build Application
        uses: docker/bake-action@37816e747588cb137173af99ab33873600c46ea8 # v6.8.0
        id: bake
        with:
          files: |
            ./docker-bake.hcl
            cwd://${{ steps.meta.outputs.bake-file }}
          set: |
            *.args.VENDOR=${{ github.repository_owner }}
            *.cache-from=${{ format('type=registry,ref=ghcr.io/{0}/build_cache:{1}-{2},mode=max', github.repository_owner, needs.plan.outputs.app, steps.target.outputs.arch) }}
            *.cache-to=${{ inputs.release && format('type=registry,ref=ghcr.io/{0}/build_cache:{1}-{2},mode=max,compression=zstd,force-compression=true', github.repository_owner, needs.plan.outputs.app, steps.target.outputs.arch) || '' }}
            *.labels.org.opencontainers.image.title=${{ needs.plan.outputs.app }}
            *.labels.org.opencontainers.image.url=https://ghcr.io/${{ github.repository_owner }}/${{ needs.plan.outputs.app }}
            *.labels.org.opencontainers.image.version=${{ needs.plan.outputs.version }}
            *.labels.org.opencontainers.image.revision=${{ github.sha }}
            *.labels.org.opencontainers.image.vendor=${{ github.repository_owner }}
            ${{ inputs.release && format('*.output=type=image,name=ghcr.io/{0}/{1},push-by-digest=true,name-canonical=true,push=true', github.repository_owner, needs.plan.outputs.app) || '*.output=type=docker' }}
            *.platform=${{ matrix.platform }}
            *.tags=
          source: .
          targets: image
          workdir: .